spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/musta
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
spring doc:
      default-produces-media-type: application/json

