spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/musta
    username: postgres
    password: 1111

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  doc:
      default-produces-media-type: application/json

  mail:
   host: smtp.gmail.com
   port: 587
   username: *********@gmail.com
   password: ********** //generate a password from https://myaccount.google.com/apppasswords
   properties:
     mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
